worker_processes auto;

events {
    worker_connections 4096;
}

http {
    client_max_body_size 16M;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen 8080;
        server_name localhost;

        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/auth/ {
            proxy_pass http://auth-service:3001/;
        }

        # Patient Service
        # External: /api/patients/* -> Internal: /patients/*
        # External: /api/patients/admin/* -> Internal: /admin/*
        location /api/patients/admin/ {
            rewrite ^/api/patients/admin/(.*)$ /admin/$1 break;
            proxy_pass http://patient-service:3002;
        }
        location /api/patients/ {
            rewrite ^/api/patients/(.*)$ /patients/$1 break;
            proxy_pass http://patient-service:3002;
        }

        location /api/doctors/ {
            proxy_pass http://doctor-service:3003/;
        }

        location /api/appointments/ {
            proxy_pass http://appointment-service:3004/;
        }

        location /api/telemedicine/ {
            proxy_pass http://telemedicine-service:3005/;
        }

        location /api/payments/ {
            proxy_pass http://payment-service:3006/;
        }

        location /api/notifications/ {
            proxy_pass http://notification-service:3007/;
        }

        location /api/ai/ {
            proxy_pass http://ai-symptom-service:3008/;
        }
    }
}
