# AI Symptom Service
spring.application.name=ai-symptom-service
server.port=3008

# MongoDB
spring.data.mongodb.uri=mongodb+srv://sadee:sadee@cluster0.rej54xx.mongodb.net/ai-symptom-service?appName=Cluster0

# CORS
cors.allowed-origins=http://localhost:3000


