# Auth Service
spring.application.name=auth-service
server.port=3001

# MongoDB
spring.data.mongodb.uri=mongodb+srv://sadee:sadee@cluster0.rej54xx.mongodb.net/auth-service?appName=Cluster0

# JWT
jwt.secret=your_super_secret_key_here_make_it_long
jwt.expiration=86400000

# CORS
cors.allowed-origins=http://localhost:3000


