apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: ghcr.io/sadeeshasathsara/medicare/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3006
          env:
            # Update the MongoDB URI below manually
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: medicare-secrets
                  key: MONGO_URI_PAYMENT

            - name: CORS_ALLOWED_ORIGINS
              valueFrom:
                secretKeyRef:
                  name: medicare-secrets
                  key: CORS_ALLOWED_ORIGINS
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 3006
      targetPort: 3006


