apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
  labels:
    app: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: ghcr.io/sadeeshasathsara/medicare/telemedicine-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3005
          env:
            # Update the MongoDB URI below manually
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: medicare-secrets
                  key: MONGO_URI_TELEMEDICINE
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  selector:
    app: telemedicine-service
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005


