# Payment Service
spring.application.name=payment-service
server.port=3006

# MongoDB
spring.data.mongodb.uri=mongodb+srv://sadee:sadee@cluster0.rej54xx.mongodb.net/payment-service?appName=Cluster0

# CORS
cors.allowed-origins=http://localhost:3000


