# Notification Service
spring.application.name=notification-service
server.port=3007

# MongoDB
spring.data.mongodb.uri=mongodb+srv://sadee:sadee@cluster0.rej54xx.mongodb.net/notification-service?appName=Cluster0

# CORS
cors.allowed-origins=http://localhost:3000


