package com.healthcare.notification.model;

public enum NotificationEventType {
    APPOINTMENT_REQUESTED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED,
    CONSULTATION_COMPLETED,
    TELEMEDICINE_APPOINTMENT_ACCEPTED,
    TELEMEDICINE_APPOINTMENT_REJECTED,
    TELEMEDICINE_APPOINTMENT_RESCHEDULED,
    TELEMEDICINE_CONSULTATION_COMPLETED,
    TELEMEDICINE_PRESCRIPTION_ISSUED
}
